const translations = {
  en: {
    'nav.about':'About','nav.experience':'Experience','nav.work':'Selected Work','nav.skills':'Skills','nav.cinema':'Cinema','nav.contact':'Contact',
    'hero.eyebrow':'BUSINESS DEVELOPMENT · MARKET INTELLIGENCE','hero.name':'Ali\nZarmali','hero.title':'Business Development & Strategic Market Research','hero.lede':'I work at the intersection of market research, business development, strategy, and technology — turning complex information into structured business insight.','hero.ctaWork':'Selected work','hero.ctaContact':'Get in touch','hero.note':'Business · Strategy · Research',
    'labels.about':'ABOUT','labels.experience':'EXPERIENCE','labels.work':'SELECTED WORK','labels.skills':'SKILLS & EDUCATION','labels.more':'PUBLICATIONS & CERTIFICATES','labels.cinema':'CINEMA','labels.contact':'CONTACT',
    'about.heading':'A business-oriented researcher with a technology background.','about.p1':'My professional path combines mechanical engineering, technology management, strategic market research, and business development. I am interested in how markets, technologies, organizations, and business models interact.','about.p2':'My work has included market research in BRICS and Eurasian markets, feasibility studies, ERA framework modeling, export-management research, startup evaluation, business-model analysis, and strategic projects across technology and industrial sectors. I hold an MBA in Technology from Allame Tabataba’i University and a B.Sc. in Mechanical Engineering from Shahrood University of Technology.',
    'facts.research':'Research','facts.researchValue':'Market · Strategy · Technology','facts.focus':'Focus','facts.focusValue':'Business Development','facts.methods':'Methods','facts.methodsValue':'Analysis · Modeling · Research','facts.interests':'Interests','facts.interestsValue':'Business · Technology · Cinema',
    'exp.nexa.date':'2025 — Present','exp.nexa.org':'NEXA SCF','exp.nexa.title':'Strategic Market Research Analyst','exp.nexa.desc':'Conducting strategic market research in BRICS and Eurasian markets; modeling ERA frameworks; preparing feasibility-study reports; researching Export Management Companies; and consulting on R&D tax-credit projects.',
    'exp.cdmc.date':'2024','exp.cdmc.org':'Alborz CDMC','exp.cdmc.title':'Market Research Analyst','exp.cdmc.desc':'Designed the market-research process and methodology and collaborated on research projects in the confectionery and dairy industries.',
    'exp.ptsi.date':'2022','exp.ptsi.org':'Presidential Technology Studies Institute','exp.ptsi.title':'Technology & Policy Research','exp.ptsi.desc':'Investigated the capacities of Iran’s Ministry of Economic Affairs and Finance for developing the FinTech ecosystem in the field of blockchain.',
    'exp.startup.date':'2021 — 2022','exp.startup.org':'Startup','exp.startup.title':'Co-Founder & CSO','exp.startup.desc':'Worked on a matchmaking and games startup, focusing on business model development and negotiations. The venture ended following legal issues and team migration.',
    'exp.greentech.date':'2020 — 2021','exp.greentech.org':'GreenTech Accelerator & Incubator','exp.greentech.title':'Research & Development Expert','exp.greentech.desc':'Developed a due-diligence and startup pitch-deck evaluation program and designed acceleration and scale-up processes.',
    'work.1.date':'2023','work.1.title':'Consumer Behavior & Marketing-Mix Evaluation','work.1.desc':'Designed and explained an evaluation model for canned products using the 4Ps and consumer behavior, and implemented an evaluation period.','work.1.methods':'Survey · Focus Groups · Content Analysis',
    'work.2.date':'2022','work.2.title':'Mustafa-Prize Evaluation Model Simulation','work.2.desc':'Simulated an evaluation model with NetLogo under academic supervision for the Mustafa Science and Technology Foundation.','work.2.methods':'Mathematical Modeling · NetLogo',
    'work.3.date':'2022','work.3.title':'Strategic Plan & Roadmap for Food Industry Holding','work.3.desc':'Contributed to the seventh five-year strategic plan and roadmap, including business-model analysis, holding strategy, VMV, and BSC.','work.3.methods':'Business Model · Strategy · VMV · BSC',
    'work.4.date':'2020 — 2021','work.4.title':'National Resilience & International Competitiveness','work.4.desc':'Worked on a plan covering housing, home appliances, and automotive industries, using value-chain analysis, PESTEL, and benchmarking.','work.4.methods':'Value Chain · PESTEL · Benchmarking',
    'skills.heading':'Tools, methods, and ways of thinking.','skills.1':'Market Research','skills.2':'Business Development','skills.3':'Strategic Analysis','skills.4':'Business Model Analysis','skills.5':'Feasibility Studies','skills.6':'PESTEL','skills.7':'Value Chain Analysis','skills.8':'Benchmarking','skills.9':'Design Thinking','skills.10':'Strategic Vision','skills.11':'Critical Thinking','skills.12':'Problem Solving','skills.13':'Microsoft Office','skills.14':'NetLogo','education.heading':'Education','education.mba':'MBA in Technology','education.mbaMeta':'Allame Tabataba’i University · 2018–2022','education.thesisLabel':'Thesis:','education.thesis':'The Role of Knowledge Diffusion Pattern in the Knowledge Level of Industrial Clusters: Insight from Agent-Based Simulation Approach','education.bsc':'B.Sc. Mechanical Engineering','education.bscMeta':'Shahrood University of Technology · 2012–2017',
    'publications.heading':'Publications','publications.1':'Atlas of Internal Capabilities of Technology Companies in Social Innovation and Agriculture — 2020','publications.2':'Global Experiences of Startup Companies in AI, FinTech and AR-VR — 2019',
    'certificates.heading':'Certificates','certificates.1':'Comprehensive Commercial & International Trade Skills','certificates.1org':'Business Training Center, 2025','certificates.1details':'NTSW · Incoterms · International Payment · Cargo Insurance · Customs Rules','certificates.2':'Launching Startup Foundation','certificates.2org':'Charkhe Academy at Maktabkhoone, 2021','certificates.2details':'Negotiations · Valuation · ESOP · KPI · SHA',
    'cinema.heading':'Outside work, I follow cinema.','cinema.sub':'Three 2026 films on my current watchlist.','movies.1':'The Rivals of Amziah King','movies.2':'The Whisper Man','movies.3':'The Invite',
    'contact.heading':'Have a business problem worth exploring?','contact.text':'If you would like to discuss a market, strategy, business opportunity, or research project, feel free to get in touch.','contact.linkedinNote':'Connect with me on LinkedIn','footer.name':'Ali Zarmali','footer':'Business Development · Market Intelligence · Strategy'
  },
  fa: {
    'nav.about':'درباره من','nav.experience':'سوابق','nav.work':'پروژه‌های منتخب','nav.skills':'مهارت‌ها','nav.cinema':'سینما','nav.contact':'ارتباط',
    'hero.eyebrow':'توسعه کسب‌وکار · هوش بازار','hero.name':'علی زرمالی','hero.title':'توسعه کسب‌وکار و تحقیقات راهبردی بازار','hero.lede':'در نقطه تلاقی تحقیقات بازار، توسعه کسب‌وکار، استراتژی و فناوری فعالیت می‌کنم و اطلاعات پیچیده را به بینش ساختاریافته کسب‌وکار تبدیل می‌کنم.','hero.ctaWork':'پروژه‌های منتخب','hero.ctaContact':'ارتباط با من','hero.note':'کسب‌وکار · استراتژی · پژوهش',
    'labels.about':'درباره من','labels.experience':'سوابق حرفه‌ای','labels.work':'پروژه‌های منتخب','labels.skills':'مهارت‌ها و تحصیلات','labels.more':'انتشارات و گواهی‌ها','labels.cinema':'سینما','labels.contact':'ارتباط',
    'about.heading':'پژوهشگر حوزه کسب‌وکار با پیشینه فناوری.','about.p1':'مسیر حرفه‌ای من ترکیبی از مهندسی مکانیک، مدیریت فناوری، تحقیقات راهبردی بازار و توسعه کسب‌وکار است. به تعامل میان بازارها، فناوری‌ها، سازمان‌ها و مدل‌های کسب‌وکار علاقه‌مندم.','about.p2':'تجربه من شامل تحقیقات بازار در بازارهای BRICS و اوراسیا، مطالعات امکان‌سنجی، مدل‌سازی چارچوب ERA، پژوهش در حوزه شرکت‌های مدیریت صادرات، ارزیابی استارتاپ‌ها، تحلیل مدل کسب‌وکار و پروژه‌های راهبردی در حوزه‌های فناوری و صنعتی است. دارای مدرک MBA مدیریت فناوری از دانشگاه علامه طباطبائی و کارشناسی مهندسی مکانیک از دانشگاه صنعتی شاهرود هستم.',
    'facts.research':'حوزه پژوهش','facts.researchValue':'بازار · استراتژی · فناوری','facts.focus':'تمرکز','facts.focusValue':'توسعه کسب‌وکار','facts.methods':'روش‌ها','facts.methodsValue':'تحلیل · مدل‌سازی · پژوهش','facts.interests':'علاقه‌مندی‌ها','facts.interestsValue':'کسب‌وکار · فناوری · سینما',
    'exp.nexa.date':'۱۴۰۴ — اکنون','exp.nexa.org':'نکسا | SCF','exp.nexa.title':'تحلیلگر تحقیقات راهبردی بازار','exp.nexa.desc':'انجام تحقیقات راهبردی بازار در بازارهای BRICS و اوراسیا؛ مدل‌سازی چارچوب‌های ERA؛ تهیه گزارش‌های مطالعات امکان‌سنجی؛ پژوهش درباره شرکت‌های مدیریت صادرات؛ و ارائه مشاوره در پروژه‌های اعتبار مالیاتی تحقیق و توسعه.',
    'exp.cdmc.date':'۱۴۰۳','exp.cdmc.org':'مرکز توسعه مدیریت زنجیره‌ای البرز','exp.cdmc.title':'تحلیلگر تحقیقات بازار','exp.cdmc.desc':'طراحی فرایند و روش‌شناسی تحقیقات بازار و همکاری در پروژه‌های پژوهشی در صنایع شیرینی و لبنیات.',
    'exp.ptsi.date':'۱۴۰۱','exp.ptsi.org':'پژوهشکده مطالعات فناوری ریاست جمهوری','exp.ptsi.title':'پژوهشگر فناوری و سیاست‌گذاری','exp.ptsi.desc':'بررسی ظرفیت‌های وزارت امور اقتصادی و دارایی ایران برای توسعه زیست‌بوم فین‌تک در حوزه بلاکچین.',
    'exp.startup.date':'۱۴۰۰ — ۱۴۰۱','exp.startup.org':'استارتاپ','exp.startup.title':'هم‌بنیان‌گذار و مدیر ارشد استراتژی','exp.startup.desc':'فعالیت در یک استارتاپ همتایابی و بازی با تمرکز بر توسعه مدل کسب‌وکار و مذاکره. این کسب‌وکار در پی مسائل حقوقی و مهاجرت اعضای تیم متوقف شد.',
    'exp.greentech.date':'۱۳۹۹ — ۱۴۰۰','exp.greentech.org':'شتاب‌دهنده و مرکز نوآوری گرین‌تک','exp.greentech.title':'کارشناس تحقیق و توسعه','exp.greentech.desc':'توسعه برنامه ارزیابی موشکافانه و ارزیابی Pitch Deck استارتاپ‌ها و طراحی فرایندهای شتاب‌دهی و مقیاس‌پذیری.',
    'work.1.date':'۱۴۰۲','work.1.title':'ارزیابی رفتار مصرف‌کننده و آمیخته بازاریابی','work.1.desc':'طراحی و تشریح مدل ارزیابی محصولات کنسروی بر مبنای 4P و رفتار مصرف‌کننده و اجرای دوره ارزیابی.','work.1.methods':'پرسشنامه · گروه‌های کانونی · تحلیل محتوا',
    'work.2.date':'۱۴۰۱','work.2.title':'شبیه‌سازی مدل ارزیابی جایزه مصطفی','work.2.desc':'شبیه‌سازی یک مدل ارزیابی با نرم‌افزار NetLogo تحت نظارت علمی برای بنیاد علم و فناوری مصطفی.','work.2.methods':'مدل‌سازی ریاضی · NetLogo',
    'work.3.date':'۱۴۰۱','work.3.title':'برنامه راهبردی و نقشه راه هلدینگ صنایع غذایی','work.3.desc':'مشارکت در تدوین برنامه راهبردی و نقشه راه هفت‌ساله شامل تحلیل مدل کسب‌وکار، استراتژی هلدینگ، VMV و BSC.','work.3.methods':'مدل کسب‌وکار · استراتژی · VMV · BSC',
    'work.4.date':'۱۳۹۹ — ۱۴۰۰','work.4.title':'تاب‌آوری ملی و رقابت‌پذیری بین‌المللی','work.4.desc':'فعالیت در طرحی برای صنایع مسکن، لوازم خانگی و خودرو با استفاده از تحلیل زنجیره ارزش، PESTEL و الگوبرداری.','work.4.methods':'زنجیره ارزش · PESTEL · الگوبرداری',
    'skills.heading':'ابزارها، روش‌ها و شیوه‌های تفکر.','skills.1':'تحقیقات بازار','skills.2':'توسعه کسب‌وکار','skills.3':'تحلیل راهبردی','skills.4':'تحلیل مدل کسب‌وکار','skills.5':'مطالعات امکان‌سنجی','skills.6':'PESTEL','skills.7':'تحلیل زنجیره ارزش','skills.8':'الگوبرداری','skills.9':'تفکر طراحی','skills.10':'چشم‌انداز راهبردی','skills.11':'تفکر انتقادی','skills.12':'حل مسئله','skills.13':'مایکروسافت آفیس','skills.14':'NetLogo','education.heading':'تحصیلات','education.mba':'MBA مدیریت فناوری','education.mbaMeta':'دانشگاه علامه طباطبائی · ۱۳۹۷–۱۴۰۱','education.thesisLabel':'عنوان پایان‌نامه:','education.thesis':'نقش الگوی انتشار دانش در سطح دانش خوشه‌های صنعتی: بینشی از رویکرد شبیه‌سازی عامل‌محور','education.bsc':'کارشناسی مهندسی مکانیک','education.bscMeta':'دانشگاه صنعتی شاهرود · ۱۳۹۱–۱۳۹۶',
    'publications.heading':'انتشارات','publications.1':'اطلس قابلیت‌های داخلی شرکت‌های فناوری در نوآوری اجتماعی و کشاورزی — ۱۳۹۹','publications.2':'تجربیات جهانی شرکت‌های استارتاپی در هوش مصنوعی، فین‌تک و AR-VR — ۱۳۹۸',
    'certificates.heading':'گواهی‌ها','certificates.1':'مهارت‌های جامع بازرگانی و تجارت بین‌الملل','certificates.1org':'مرکز آموزش بازرگانی، ۱۴۰۴','certificates.1details':'سامانه جامع تجارت · اینکوترمز · پرداخت بین‌المللی · بیمه بار · مقررات گمرکی','certificates.2':'مبانی راه‌اندازی استارتاپ','certificates.2org':'آکادمی چرخ، مکتب‌خونه، ۱۴۰۰','certificates.2details':'مذاکره · ارزش‌گذاری · ESOP · KPI · SHA',
    'cinema.heading':'خارج از کار، سینما را دنبال می‌کنم.','cinema.sub':'سه فیلم ۲۰۲۶ که در فهرست فعلی تماشای من هستند.','movies.1':'رقیبان امزیا کینگ','movies.2':'مرد نجواگر','movies.3':'دعوت',
    'contact.heading':'یک مسئله کسب‌وکاری برای بررسی دارید؟','contact.text':'اگر مایلید درباره یک بازار، استراتژی، فرصت کسب‌وکار یا پروژه پژوهشی گفت‌وگو کنیم، خوشحال می‌شوم در ارتباط باشیم.','contact.linkedinNote':'در لینکدین با من در ارتباط باشید','footer.name':'علی زرمالی','footer':'توسعه کسب‌وکار · هوش بازار · استراتژی'
  }
};

let currentLang = localStorage.getItem('siteLang') || 'en';
function applyLanguage(lang){
  currentLang=lang; localStorage.setItem('siteLang',lang);
  document.documentElement.lang=lang; document.documentElement.dir=lang==='fa'?'rtl':'ltr';
  document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(!(key==='hero.name') && translations[lang][key]) el.textContent=translations[lang][key];});
  const nameEl=document.querySelector('[data-i18n="hero.name"]');
  if(nameEl){ if(lang==='fa'){nameEl.innerHTML='علی زرمالی';} else {nameEl.innerHTML='Ali<br><span>Zarmali</span>'; } }
  document.getElementById('langToggle').textContent=lang==='en'?'FA':'EN';
}
document.getElementById('langToggle').addEventListener('click',()=>applyLanguage(currentLang==='en'?'fa':'en'));
document.getElementById('year').textContent=new Date().getFullYear();
applyLanguage(currentLang);
